server:
  port: 4007
  
spring:
  datasource:
    url: jdbc:h2:mem:order-sec-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
        
camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
    filter:
      create: All
    license-file: file:${user.home}/.camunda/license.txt